/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GamePanel */

#ifndef _Included_GamePanel
#define _Included_GamePanel
#ifdef __cplusplus
extern "C" {
#endif
#undef GamePanel_FOCUS_TRAVERSABLE_UNKNOWN
#define GamePanel_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef GamePanel_FOCUS_TRAVERSABLE_DEFAULT
#define GamePanel_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef GamePanel_FOCUS_TRAVERSABLE_SET
#define GamePanel_FOCUS_TRAVERSABLE_SET 2L
#undef GamePanel_TOP_ALIGNMENT
#define GamePanel_TOP_ALIGNMENT 0.0f
#undef GamePanel_CENTER_ALIGNMENT
#define GamePanel_CENTER_ALIGNMENT 0.5f
#undef GamePanel_BOTTOM_ALIGNMENT
#define GamePanel_BOTTOM_ALIGNMENT 1.0f
#undef GamePanel_LEFT_ALIGNMENT
#define GamePanel_LEFT_ALIGNMENT 0.0f
#undef GamePanel_RIGHT_ALIGNMENT
#define GamePanel_RIGHT_ALIGNMENT 1.0f
#undef GamePanel_serialVersionUID
#define GamePanel_serialVersionUID -7644114512714619750LL
#undef GamePanel_serialVersionUID
#define GamePanel_serialVersionUID 4613797578919906343LL
#undef GamePanel_INCLUDE_SELF
#define GamePanel_INCLUDE_SELF 1L
#undef GamePanel_SEARCH_HEAVYWEIGHTS
#define GamePanel_SEARCH_HEAVYWEIGHTS 1L
#undef GamePanel_NOT_OBSCURED
#define GamePanel_NOT_OBSCURED 0L
#undef GamePanel_PARTIALLY_OBSCURED
#define GamePanel_PARTIALLY_OBSCURED 1L
#undef GamePanel_COMPLETELY_OBSCURED
#define GamePanel_COMPLETELY_OBSCURED 2L
#undef GamePanel_WHEN_FOCUSED
#define GamePanel_WHEN_FOCUSED 0L
#undef GamePanel_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define GamePanel_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef GamePanel_WHEN_IN_FOCUSED_WINDOW
#define GamePanel_WHEN_IN_FOCUSED_WINDOW 2L
#undef GamePanel_UNDEFINED_CONDITION
#define GamePanel_UNDEFINED_CONDITION -1L
#undef GamePanel_IS_DOUBLE_BUFFERED
#define GamePanel_IS_DOUBLE_BUFFERED 0L
#undef GamePanel_ANCESTOR_USING_BUFFER
#define GamePanel_ANCESTOR_USING_BUFFER 1L
#undef GamePanel_IS_PAINTING_TILE
#define GamePanel_IS_PAINTING_TILE 2L
#undef GamePanel_IS_OPAQUE
#define GamePanel_IS_OPAQUE 3L
#undef GamePanel_KEY_EVENTS_ENABLED
#define GamePanel_KEY_EVENTS_ENABLED 4L
#undef GamePanel_FOCUS_INPUTMAP_CREATED
#define GamePanel_FOCUS_INPUTMAP_CREATED 5L
#undef GamePanel_ANCESTOR_INPUTMAP_CREATED
#define GamePanel_ANCESTOR_INPUTMAP_CREATED 6L
#undef GamePanel_WIF_INPUTMAP_CREATED
#define GamePanel_WIF_INPUTMAP_CREATED 7L
#undef GamePanel_ACTIONMAP_CREATED
#define GamePanel_ACTIONMAP_CREATED 8L
#undef GamePanel_CREATED_DOUBLE_BUFFER
#define GamePanel_CREATED_DOUBLE_BUFFER 9L
#undef GamePanel_IS_PRINTING
#define GamePanel_IS_PRINTING 11L
#undef GamePanel_IS_PRINTING_ALL
#define GamePanel_IS_PRINTING_ALL 12L
#undef GamePanel_IS_REPAINTING
#define GamePanel_IS_REPAINTING 13L
#undef GamePanel_WRITE_OBJ_COUNTER_FIRST
#define GamePanel_WRITE_OBJ_COUNTER_FIRST 14L
#undef GamePanel_RESERVED_1
#define GamePanel_RESERVED_1 15L
#undef GamePanel_RESERVED_2
#define GamePanel_RESERVED_2 16L
#undef GamePanel_RESERVED_3
#define GamePanel_RESERVED_3 17L
#undef GamePanel_RESERVED_4
#define GamePanel_RESERVED_4 18L
#undef GamePanel_RESERVED_5
#define GamePanel_RESERVED_5 19L
#undef GamePanel_RESERVED_6
#define GamePanel_RESERVED_6 20L
#undef GamePanel_WRITE_OBJ_COUNTER_LAST
#define GamePanel_WRITE_OBJ_COUNTER_LAST 21L
#undef GamePanel_REQUEST_FOCUS_DISABLED
#define GamePanel_REQUEST_FOCUS_DISABLED 22L
#undef GamePanel_INHERITS_POPUP_MENU
#define GamePanel_INHERITS_POPUP_MENU 23L
#undef GamePanel_OPAQUE_SET
#define GamePanel_OPAQUE_SET 24L
#undef GamePanel_AUTOSCROLLS_SET
#define GamePanel_AUTOSCROLLS_SET 25L
#undef GamePanel_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define GamePanel_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef GamePanel_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define GamePanel_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     GamePanel
 * Method:    getFiguresArray
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_GamePanel_getFiguresArray
  (JNIEnv *, jclass);

/*
 * Class:     GamePanel
 * Method:    getFigureFromArray
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GamePanel_getFigureFromArray
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     GamePanel
 * Method:    getInitArray
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_GamePanel_getInitArray
  (JNIEnv *, jclass);

/*
 * Class:     GamePanel
 * Method:    gameOver
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_GamePanel_gameOver
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
