/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InputHandler */

#ifndef _Included_InputHandler
#define _Included_InputHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InputHandler
 * Method:    passCellXY
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_InputHandler_passCellXY
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InputHandler
 * Method:    selectFigure
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_InputHandler_selectFigure
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InputHandler
 * Method:    moveFigure
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_InputHandler_moveFigure
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
